Update creation.lua [ Fix Error : handler (@PolyZone/creation/server/…
mkafrin/PolyZone pull request #111
Opened 2024-12-25 02:27 UTC by subhampro

…creation.lua:22]

This error coming because of latest Artifacts !!!

09:41:45 AM [ script:PolyZone] SCRIPT ERROR: @PolyZone/creation/server/creation.lua:22: attempt to call a nil value (field 'output')
09:41:45 AM [ script:PolyZone] > handler (@PolyZone/creation/server/creation.lua:22)

Fixed !!!

> This code uses LoadResourceFile to read the existing content of the file and SaveResourceFile to save the updated content, ensuring that the file operations are handled correctly in the FiveM environment.

2025-01-03 03:57 UTC, mkafrin requested changes
This has a lot of unrelated changes put together, as well as some I'm not particularly comfortable with. I appreciate the PR, but would feel much better if it was single focus (just fixing the IO writing issue), and then you made separate ones for the other stuff, upon which we could discuss further. You're welcome to update this to just be that fix (or make a new PR with just the fix), or I can pull it out myself. If you are going to move forward with doing that, please see all the comments I wrote. Thank you for the contribution.

2025-01-03 03:57 UTC, mkafrin commented on polyzone_created_zones.txt
> +BoxZone:Create(
This should not be committed

2025-01-03 03:57 UTC, mkafrin commented on fxmanifest.lua
> +version '2.6.0'
Versions should not be downgraded, that's not how semver works. Patch version changes are for fixes that don't cause breaking changes. This does cause a breaking change (removing the config), which would normally entail a major version bump (3.x.x), but as mentioned in the other comment, we just shouldn't be removing that config. The ability to save zones both ways is a feature, and it def shouldn't be removed in a "fix this error" PR. Ideally, if this PR were just fixing the save error, the correct version bump would be `2.6.2`.

2025-01-03 03:57 UTC, mkafrin commented on creation/server/creation.lua
> +local parse = {
These don't need to be in a table. They were fine as freestanding functions. Also, please don't remove the logic to parse them both ways (depending on the `ConfigFormatEnabled` field).

2025-01-03 03:57 UTC, mkafrin commented on creation/server/config.lua
> -Config.ConfigFormatEnabled = false
Please don't remove this.

2025-01-03 03:57 UTC, mkafrin commented on creation/client/utils.lua
> -      DisableControlAction(0, 36, true)   -- Ctrl
Is there a reason you removed this and instead put it in all the individual places?

2025-01-03 03:57 UTC, mkafrin commented on creation/client/CircleZone.lua
> +  if IsDisabledControlJustPressed(0, 99) then
Please don't remove comments.

2025-01-03 03:57 UTC, mkafrin commented on creation/client/CircleZone.lua
> +  if IsDisabledControlJustPressed(0, 81) then
Please don't remove comments.

2025-01-03 03:57 UTC, mkafrin commented on creation/client/BoxZone.lua
> +  if IsDisabledControlJustPressed(0, 99) then
Please don't remove comments.

2025-01-03 03:57 UTC, mkafrin commented on creation/client/BoxZone.lua
> +  if IsDisabledControlJustPressed(0, 81) then
Please don't remove comments.

2025-01-03 03:57 UTC, mkafrin commented on creation/client/BoxZone.lua
> +    if IsDisabledControlJustPressed(0, 99) then
Please don't remove comments.

2025-01-03 03:57 UTC, mkafrin commented on creation/client/BoxZone.lua
> +    if IsDisabledControlJustPressed(0, 81) then
Please don't remove comments.

2025-01-03 03:57 UTC, mkafrin commented on client.lua
> -  if not forceDraw and not self.debugPoly and not self.debugGrid then return end
Why was `forceDraw` removed?

2025-01-03 03:57 UTC, mkafrin commented on BoxZone.lua
> -function BoxZone.calculateMinAndMaxZ(minZ, maxZ, scaleZ, offsetZ)
Why was this removed?

2025-01-03 05:02 UTC, subhampro reviewed
Check my new commit and feel free to share your suggestions !

2025-01-03 05:02 UTC, subhampro commented on BoxZone.lua
> -function BoxZone.calculateMinAndMaxZ(minZ, maxZ, scaleZ, offsetZ)
My bad !
In next commit I will restore the function wwhich Handles Z-axis scaling and offset calculations for BoxZones,
Properly warns when trying to scale Z values when not all Z coordinates are provided and 
Maintains compatibility with the existing BoxZone functionality.

2025-01-03 05:08 UTC, subhampro commented on creation/server/config.lua
> -Config.ConfigFormatEnabled = false
Added it back !

2025-01-04 06:51 UTC, mkafrin commented on creation/server/creation.lua
> +local parse = {
Thank you!

2025-01-04 06:55 UTC, mkafrin commented on client.lua
> -  if not forceDraw and not self.debugPoly and not self.debugGrid then return end
No judgement, genuinely curious: Are you using AI to do any of this code or generate these responses? Don't have anything against it if the code works, it just gave me deja vu of the few times I've used chatgpt to code something lol.

2025-01-04 07:03 UTC, mkafrin requested changes

2025-01-04 07:03 UTC, mkafrin commented on BoxZone.lua
> -      zone:draw(false)
forceDraw param passing should be restored in all places

2025-01-04 07:03 UTC, mkafrin commented on BoxZone.lua
> -  local minZ, maxZ = BoxZone.calculateMinAndMaxZ(options.minZ, options.maxZ, scaleZ, offsetZ)
calculateMinAndMaxZ still removed. If you can give a valid reason as to why, that's fine. Otherwise, please restore.

2025-01-04 07:03 UTC, mkafrin commented on BoxZone.lua
> +    return false
extra spacing

2025-01-04 07:03 UTC, mkafrin commented on CircleZone.lua
> +
extra spacing

2025-01-04 07:03 UTC, mkafrin commented on CircleZone.lua
> +function CircleZone:draw()
restore param

2025-01-04 07:03 UTC, mkafrin commented on ComboZone.lua
> +function ComboZone:draw()
restore param

2025-01-04 07:03 UTC, mkafrin commented on client.lua
> +
extra spacing

2025-01-04 07:05 UTC, subhampro commented on client.lua
> -  if not forceDraw and not self.debugPoly and not self.debugGrid then return end
No worries at all, and thanks for checking! Yes, I've been using AI tools to assist me with some coding tasks and generating responses. It's been incredibly helpful for speeding up the process and ensuring accuracy. I'm glad you appreciate the results!

2025-01-04 07:18 UTC, subhampro commented on client.lua
> +    return false
Unfortunately I love spacing which is bad habit and unnecessary !! Will remove on next repo !

2025-01-04 07:19 UTC, subhampro commented on client.lua
> +
Unfortunately I love spacing which is bad habit and unnecessary !! Will remove on next repo !

2025-01-04 07:19 UTC, subhampro commented on client.lua
> +
Unfortunately I love spacing which is bad habit and unnecessary !! Will remove on next repo !

2025-01-04 07:19 UTC, subhampro commented on client.lua
> +
Unfortunately I love spacing which is bad habit and unnecessary !! Will remove on next repo !

2025-01-04 07:19 UTC, subhampro commented on creation/client/BoxZone.lua
> +
Unfortunately I love spacing which is bad habit and unnecessary !! Will remove on next repo !

2025-01-04 07:20 UTC, subhampro commented on creation/client/BoxZone.lua
> +
Unfortunately I love spacing which is bad habit and unnecessary !! Will remove on next repo !

2025-01-04 07:27 UTC, subhampro commented on creation/client/utils.lua
> +  DisableControlAction(0, 36, true)
Oh Sad to see I missed it, we had two bouncers doing the same job ! I fixed this redundancy party by letting disableControlKeyInput handle all the control blocking while handleArrowInput focuses on its actual job on my next commit !

2025-01-04 07:30 UTC, subhampro commented on BoxZone.lua
> -      zone:draw(false)
Yo I didn't see that !! You gave good eye sight !! Fixed on next commit !

2025-01-04 07:32 UTC, subhampro commented on BoxZone.lua
> -  local minZ, maxZ = BoxZone.calculateMinAndMaxZ(options.minZ, options.maxZ, scaleZ, offsetZ)
The functionality of `calculateMinAndMaxZ` was accidentally removed. I added it back in the next commit!

2025-01-04 07:35 UTC, subhampro commented on BoxZone.lua
> +    return false
removed !

2025-01-04 07:35 UTC, subhampro commented on CircleZone.lua
> +
removed!

2025-01-04 07:37 UTC, subhampro commented on CircleZone.lua
> +function CircleZone:draw()
Restored I missed on previous commit !

2025-01-04 07:40 UTC, subhampro commented on ComboZone.lua
> +function ComboZone:draw()
restored !

2025-01-04 07:41 UTC, subhampro commented on client.lua
> +
removed !

2025-01-04 23:40 UTC, mkafrin commented
Several of the things I requested to be fixed still are not, and new issues and unrelated code were introduced. I wouldn't have a problem with allowing AI help here, if it worked, but clearly, it's not ready for the limelight. I'll add the targeted fix myself and close this PR. I appreciate bringing the issue to my attention, but I would suggest you try to do some learning of fundamentals, rather than relying on AI.

2025-01-04 23:40 UTC, closed without merging